-- =========================================================================
-- ORASSADM - MODELE METIER ASSURANCE COMPLET
-- Partie 1 : TABLES
-- =========================================================================
-- Execution : ORASSADM/ORASSADM@192.168.108.134:1521/ORASSUITPDB
-- =========================================================================
SET SERVEROUTPUT ON SIZE 1000000
SPOOL d:\ProjetApexOrassuit\metier_result.txt

-- =============================================
-- TABLE 1 : AGENCES
-- =============================================
CREATE TABLE agences (
    id_agence      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_agence    VARCHAR2(10) NOT NULL UNIQUE,
    nom_agence     VARCHAR2(200) NOT NULL,
    adresse        VARCHAR2(500),
    ville          VARCHAR2(100),
    pays           VARCHAR2(100) DEFAULT 'Maroc',
    telephone      VARCHAR2(20),
    email          VARCHAR2(255),
    date_creation  DATE DEFAULT SYSDATE,
    actif          VARCHAR2(1) DEFAULT 'O' CHECK (actif IN ('O','N'))
);

-- =============================================
-- TABLE 2 : AGENTS (Courtiers / Commerciaux)
-- =============================================
CREATE TABLE agents (
    id_agent       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_agence      NUMBER REFERENCES agences(id_agence),
    matricule      VARCHAR2(20) NOT NULL UNIQUE,
    nom            VARCHAR2(100) NOT NULL,
    prenom         VARCHAR2(100) NOT NULL,
    email          VARCHAR2(255),
    telephone      VARCHAR2(20),
    date_embauche  DATE DEFAULT SYSDATE,
    actif          VARCHAR2(1) DEFAULT 'O' CHECK (actif IN ('O','N'))
);

-- =============================================
-- TABLE 3 : CLIENTS (Assures)
-- =============================================
CREATE TABLE clients (
    id_client           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_client         VARCHAR2(20) DEFAULT 'PERSONNE' CHECK (type_client IN ('PERSONNE','ENTREPRISE')),
    numero_client       VARCHAR2(20) NOT NULL UNIQUE,
    nom                 VARCHAR2(100) NOT NULL,
    prenom              VARCHAR2(100),
    raison_sociale      VARCHAR2(300),
    date_naissance      DATE,
    cin                 VARCHAR2(20),
    adresse             VARCHAR2(500),
    ville               VARCHAR2(100),
    code_postal         VARCHAR2(10),
    pays                VARCHAR2(100) DEFAULT 'Maroc',
    telephone           VARCHAR2(20),
    email               VARCHAR2(255),
    id_agent            NUMBER REFERENCES agents(id_agent),
    date_creation       DATE DEFAULT SYSDATE,
    actif               VARCHAR2(1) DEFAULT 'O' CHECK (actif IN ('O','N'))
);

-- =============================================
-- TABLE 4 : BRANCHES D'ASSURANCE
-- =============================================
CREATE TABLE branches (
    id_branche     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_branche   VARCHAR2(10) NOT NULL UNIQUE,
    libelle        VARCHAR2(200) NOT NULL,
    description    VARCHAR2(1000),
    actif          VARCHAR2(1) DEFAULT 'O'
);

-- =============================================
-- TABLE 5 : PRODUITS D'ASSURANCE
-- =============================================
CREATE TABLE produits (
    id_produit     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_branche     NUMBER REFERENCES branches(id_branche),
    code_produit   VARCHAR2(20) NOT NULL UNIQUE,
    nom_produit    VARCHAR2(200) NOT NULL,
    description    VARCHAR2(1000),
    prime_min      NUMBER(15,2),
    prime_max      NUMBER(15,2),
    duree_mois     NUMBER DEFAULT 12,
    actif          VARCHAR2(1) DEFAULT 'O'
);

-- =============================================
-- TABLE 6 : CONTRATS (Polices)
-- =============================================
CREATE TABLE contrats (
    id_contrat       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_police    VARCHAR2(30) NOT NULL UNIQUE,
    id_client        NUMBER REFERENCES clients(id_client),
    id_produit       NUMBER REFERENCES produits(id_produit),
    id_agent         NUMBER REFERENCES agents(id_agent),
    date_effet       DATE NOT NULL,
    date_expiration  DATE NOT NULL,
    prime_annuelle   NUMBER(15,2),
    capital_assure   NUMBER(15,2),
    statut           VARCHAR2(20) DEFAULT 'ACTIF' CHECK (statut IN ('ACTIF','SUSPENDU','RESILIE','EXPIRE','EN_ATTENTE')),
    mode_paiement    VARCHAR2(20) DEFAULT 'ANNUEL' CHECK (mode_paiement IN ('MENSUEL','TRIMESTRIEL','SEMESTRIEL','ANNUEL')),
    date_creation    DATE DEFAULT SYSDATE
);

-- =============================================
-- TABLE 7 : GARANTIES (Couvertures du contrat)
-- =============================================
CREATE TABLE garanties (
    id_garantie      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_contrat       NUMBER REFERENCES contrats(id_contrat),
    code_garantie    VARCHAR2(20) NOT NULL,
    libelle          VARCHAR2(300) NOT NULL,
    montant_couvert  NUMBER(15,2),
    franchise        NUMBER(15,2) DEFAULT 0,
    actif            VARCHAR2(1) DEFAULT 'O'
);

-- =============================================
-- TABLE 8 : SINISTRES (Declarations)
-- =============================================
CREATE TABLE sinistres (
    id_sinistre       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_sinistre   VARCHAR2(30) NOT NULL UNIQUE,
    id_contrat        NUMBER REFERENCES contrats(id_contrat),
    date_survenance   DATE NOT NULL,
    date_declaration  DATE DEFAULT SYSDATE,
    type_sinistre     VARCHAR2(50),
    description       VARCHAR2(2000),
    lieu_sinistre     VARCHAR2(500),
    montant_estime    NUMBER(15,2),
    montant_indemnise NUMBER(15,2),
    statut            VARCHAR2(20) DEFAULT 'OUVERT' CHECK (statut IN ('OUVERT','EN_COURS','EXPERTISE','INDEMNISE','REJETE','CLOS')),
    date_cloture      DATE
);

-- =============================================
-- TABLE 9 : QUITTANCES (Paiements de prime)
-- =============================================
CREATE TABLE quittances (
    id_quittance     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_quittance VARCHAR2(30) NOT NULL UNIQUE,
    id_contrat       NUMBER REFERENCES contrats(id_contrat),
    date_emission    DATE DEFAULT SYSDATE,
    date_echeance    DATE NOT NULL,
    montant          NUMBER(15,2) NOT NULL,
    montant_paye     NUMBER(15,2) DEFAULT 0,
    statut           VARCHAR2(20) DEFAULT 'EMISE' CHECK (statut IN ('EMISE','PAYEE','PARTIELLEMENT_PAYEE','ANNULEE','IMPAYEE')),
    date_paiement    DATE
);

-- =============================================
-- TABLE 10 : PIECES JOINTES (Documents)
-- =============================================
CREATE TABLE pieces_jointes (
    id_piece         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_entite      VARCHAR2(20) NOT NULL, -- CONTRAT, SINISTRE, CLIENT
    id_entite        NUMBER NOT NULL,
    nom_fichier      VARCHAR2(300) NOT NULL,
    type_document    VARCHAR2(100),
    taille           NUMBER,
    date_ajout       DATE DEFAULT SYSDATE
);

DBMS_OUTPUT.PUT_LINE('TABLES: Toutes les tables creees avec succes');

SPOOL OFF
EXIT;
