-- =========================================================================
-- SCHÉMA ORASSADM : LE CŒUR MÉTIER (Tables, Vues, Packages JSON)
-- =========================================================================
-- Ce schéma ne contient AUCUNE interface APEX. Il gère la data et les règles.

-- 1. Création des tables d'assurance
CREATE TABLE orassadm.ass_clients (
    id_client NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(100),
    prenom VARCHAR2(100),
    email VARCHAR2(255),
    telephone VARCHAR2(20)
);

CREATE TABLE orassadm.ass_contrats (
    id_contrat NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_client NUMBER REFERENCES orassadm.ass_clients(id_client),
    type_assurance VARCHAR2(50), -- AUTO, HABITATION, SANTE
    date_effet DATE,
    statut VARCHAR2(20) DEFAULT 'ACTIF'
);

-- 2. Package Métier exposant du JSON (Utilisation de SQL/JSON standard Oracle ou PLJSON)
CREATE OR REPLACE PACKAGE orassadm.pkg_api_contrats AS
    -- Fonction qui retourne les détails d'un contrat au format JSON
    FUNCTION get_contrats_json(p_id_client IN NUMBER DEFAULT NULL) RETURN CLOB;
    
    -- Procédure pour créer un nouveau contrat (Consommée via ORDS)
    PROCEDURE creer_contrat(
        p_id_client IN NUMBER, 
        p_type IN VARCHAR2, 
        p_retour_json OUT CLOB
    );
END pkg_api_contrats;
/

CREATE OR REPLACE PACKAGE BODY orassadm.pkg_api_contrats AS

    FUNCTION get_contrats_json(p_id_client IN NUMBER DEFAULT NULL) RETURN CLOB IS
        l_json CLOB;
    BEGIN
        -- Génération JSON native (remplace PLJSON sur les versions récentes pour plus de perf)
        -- Si vous êtes en 21c, JSON_ARRAY et JSON_OBJECT sont natifs.
        SELECT JSON_ARRAYAGG(
                 JSON_OBJECT(
                     'id_contrat' VALUE c.id_contrat,
                     'type_assurance' VALUE c.type_assurance,
                     'date_effet' VALUE TO_CHAR(c.date_effet, 'YYYY-MM-DD'),
                     'statut' VALUE c.statut,
                     'client' VALUE JSON_OBJECT('nom' VALUE cl.nom, 'prenom' VALUE cl.prenom)
                 )
               ) INTO l_json
        FROM orassadm.ass_contrats c
        JOIN orassadm.ass_clients cl ON c.id_client = cl.id_client
        WHERE (p_id_client IS NULL OR c.id_client = p_id_client);
        
        RETURN l_json;
    END get_contrats_json;

    PROCEDURE creer_contrat(p_id_client IN NUMBER, p_type IN VARCHAR2, p_retour_json OUT CLOB) IS
        l_id_contrat NUMBER;
    BEGIN
        INSERT INTO orassadm.ass_contrats (id_client, type_assurance, date_effet)
        VALUES (p_id_client, p_type, SYSDATE)
        RETURNING id_contrat INTO l_id_contrat;
        
        COMMIT;
        
        p_retour_json := '{"status": "SUCCESS", "message": "Contrat créé", "id_contrat": ' || l_id_contrat || '}';
    END creer_contrat;

END pkg_api_contrats;
/

-- 3. Activation de ORDS (REST) sur le schéma et le package
-- Cela transforme vos packages métier en API Web sans modifier APEX
BEGIN
  -- Activer ORDS pour les packages ORASSADM
  ORDS.enable_schema(
    p_enabled             => TRUE,
    p_schema              => 'ORASSADM',
    p_url_mapping_type    => 'BASE_PATH',
    p_url_mapping_pattern => 'assurances_api',
    p_auto_rest_auth      => FALSE
  );
  
  -- Exposer le package spécifiquement
  ORDS.enable_object (
    p_enabled      => TRUE,
    p_schema       => 'ORASSADM',
    p_object       => 'PKG_API_CONTRATS',
    p_object_type  => 'PACKAGE',
    p_object_alias => 'contrats'
  );
END;
/
