prompt --application/pages/page_00006
begin
--   Manifest
--     PAGE: 00006
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2023.10.31'
,p_release=>'23.2.0'
,p_default_workspace_id=>2707318103396070
,p_default_application_id=>102
,p_default_id_offset=>0
,p_default_owner=>'ORASSADM'
);
wwv_flow_imp_page.create_page(
 p_id=>6
,p_name=>'Liste des Clients'
,p_alias=>'LISTE-DES-CLIENTS'
,p_step_title=>'Liste des Clients'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'18'
,p_last_updated_by=>'ADMIN'
,p_last_upd_yyyymmddhh24miss=>'20260228194654'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(3753687527040328)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(3543981091471142)
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(3428354270470637)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>wwv_flow_imp.id(3606359988471423)
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(3754382552040335)
,p_plug_name=>'Liste des Clients'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(3521737664471084)
,p_plug_display_sequence=>10
,p_location=>'WEB_SOURCE'
,p_web_src_module_id=>wwv_flow_imp.id(3752405544018348)
,p_query_type=>'SQL'
,p_plug_source_type=>'NATIVE_IR'
,p_prn_page_header=>'Liste des Clients'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(3754487733040335)
,p_name=>'Liste des Clients'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_owner=>'ADMIN'
,p_internal_uid=>3754487733040335
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3754806551040346)
,p_db_column_name=>'CIN'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'Cin'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3755213817040350)
,p_db_column_name=>'NOM'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Nom'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3755617916040350)
,p_db_column_name=>'PAYS'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Pays'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3756095350040351)
,p_db_column_name=>'EMAIL'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Email'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3756495619040351)
,p_db_column_name=>'VILLE'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Ville'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3756873838040351)
,p_db_column_name=>'PRENOM'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Prenom'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3757263758040351)
,p_db_column_name=>'STATUT'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Statut'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3757610620040351)
,p_db_column_name=>'ADRESSE'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Adresse'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3758006301040353)
,p_db_column_name=>'AGENT_NOM'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Agent Nom'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3758410562040353)
,p_db_column_name=>'ID_CLIENT'
,p_display_order=>10
,p_column_identifier=>'J'
,p_column_label=>'Id Client'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3758825732040353)
,p_db_column_name=>'TELEPHONE'
,p_display_order=>11
,p_column_identifier=>'K'
,p_column_label=>'Telephone'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3759254674040353)
,p_db_column_name=>'NOM_AGENCE'
,p_display_order=>12
,p_column_identifier=>'L'
,p_column_label=>'Nom Agence'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3759611414040353)
,p_db_column_name=>'CODE_POSTAL'
,p_display_order=>13
,p_column_identifier=>'M'
,p_column_label=>'Code Postal'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3760081441040354)
,p_db_column_name=>'TYPE_CLIENT'
,p_display_order=>14
,p_column_identifier=>'N'
,p_column_label=>'Type Client'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3760457781040354)
,p_db_column_name=>'NUMERO_CLIENT'
,p_display_order=>15
,p_column_identifier=>'O'
,p_column_label=>'Numero Client'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3760890260040354)
,p_db_column_name=>'DATE_NAISSANCE'
,p_display_order=>16
,p_column_identifier=>'P'
,p_column_label=>'Date Naissance'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3761278213040354)
,p_db_column_name=>'RAISON_SOCIALE'
,p_display_order=>17
,p_column_identifier=>'Q'
,p_column_label=>'Raison Sociale'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(3761810461042668)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'37619'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'CIN:NOM:PAYS:EMAIL:VILLE:PRENOM:STATUT:ADRESSE:AGENT_NOM:ID_CLIENT:TELEPHONE:NOM_AGENCE:CODE_POSTAL:TYPE_CLIENT:NUMERO_CLIENT:DATE_NAISSANCE:RAISON_SOCIALE'
);
wwv_flow_imp.component_end;
end;
/
